version: '3.6'

services:
  mongodb:
    image: mongo:4.2.3-bionic
    container_name: my-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=valentini
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongodb:/data/db
      - ./mongoconfig:/data/configdb
    networks:
      - mongo-compose-network

networks:
    mongo-compose-network:
      driver: bridge